# 🧠 Supervised Learning

## 🔹 0. Setup (RUN FIRST)


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


## 🔹 1. Features vs Labels

In [ ]:
data = load_iris()
X = pd.DataFrame(data.data, columns=data.feature_names)
# Creates a table (DataFrame) of features with column names
# We convert it to a DataFrame so we can see and work with labeled columns instead of just raw numbers.
y = data.target
print(y[:150])
print("Label names:", data.target_names)
X.head()


## 🔹 2. Train/Test Split


In [4]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)


## 🔹 3. Train Model


In [ ]:
# Creates a logistic regression model, max_iter=200 = max training steps
model = LogisticRegression(max_iter=200)
# Trains the model using training data
model.fit(X_train,y_train)


## 🔹 4. Predictions

In [ ]:
# Predicts labels for test data
y_pred = model.predict(X_test)
# Shows first 10 predictions
y_pred[:10]


## 🔹 5. Evaluation


In [ ]:
# Computes % of correct predictions
print("Accuracy:", accuracy_score(y_test,y_pred))
# Shows true vs predicted counts
print(confusion_matrix(y_test,y_pred))
# Shows precision, recall, F1 score
print(classification_report(y_test,y_pred))

how would this read 
[[8  2  0]
 [1  7  1]
 [0  2  9]]


## 🔹 6. Overfitting Demo

In [ ]:
# Trains model on ALL data (bad practice)
model.fit(X,y)
# Evaluates on same data → artificially high accuracy
print("Train=test accuracy:", accuracy_score(y, model.predict(X)))


## 🔹 7. Model Tuning


In [ ]:
# Loops over different tree depths
for depth in [1,2,3,5,10]:
    # Creates a decision tree with a specific depth
    tree = DecisionTreeClassifier(max_depth=depth)
    # Trains the tree
    tree.fit(X_train,y_train)
    # Prints depth + test accuracy
    print(depth, accuracy_score(y_test, tree.predict(X_test)))


## 🔹 8. Train vs Test

In [ ]:
# Creates a tree with depth = 5
tree = DecisionTreeClassifier(max_depth=5)
# Trains the model
tree.fit(X_train,y_train)

# Accuracy on training data
print("Train:", accuracy_score(y_train, tree.predict(X_train)))
# Accuracy on test data
print("Test:", accuracy_score(y_test, tree.predict(X_test)))


## 🔹 9. Imbalanced Data


In [ ]:
# Creates labels: all zeros
y_imbalanced = np.zeros(len(y))
# Sets first 10 samples as class 1 (rare class)
y_imbalanced[:10]=1

# Splits new dataset
X_train,X_test,y_train,y_test=train_test_split(X,y_imbalanced,test_size=0.2)

# Trains model
model.fit(X_train,y_train)
# Predicts labels
y_pred=model.predict(X_test)

# Computes accuracy (misleadingly high)
print("Accuracy:", accuracy_score(y_test,y_pred))
# Shows precision/recall (reveals problem)
print(classification_report(y_test,y_pred))


## 🔹 10. Challenge

🎯 Point: apply everything  

“Try to get best test accuracy without overfitting”

Look for:
- balanced train/test accuracy
- reasonable model complexity


## 🎮 Model Tuning – What You Can Try

Here are the main parameters ("knobs") you can adjust to improve your model:

---

### 🔹 1. Decision Tree (most important)

**max_depth**  
> Controls how complex the tree is  
- Small → simple model (may underfit)  
- Large → complex model (may overfit)  

Example: DecisionTreeClassifier(max_depth=3)

---

**min_samples_split**  
> Minimum number of samples required to split a node  
- Larger value → fewer splits → simpler model  

Example: DecisionTreeClassifier(min_samples_split=5)

---

**min_samples_leaf**  
> Minimum number of samples in a leaf node  
- Helps prevent overfitting  

Example: DecisionTreeClassifier(min_samples_leaf=3)

---

### 🔹 2. Logistic Regression

**C (regularization strength)**  
> Controls model complexity  
- Small C → simpler model  
- Large C → more flexible model  

Example: LogisticRegression(C=0.1)

---

**max_iter**  
> Number of training iterations  
- Increase if model does not converge  

Example: LogisticRegression(max_iter=500)

---

### 🔹 3. Train/Test Split

**test_size**  
> Fraction of data used for testing  

Example: train_test_split(X, y, test_size=0.3)

---

**random_state**  
> Controls how the data is split  

Example: train_test_split(X, y, random_state=1)

---

### 🔹 4. Model Choice

Try different models:

Example: LogisticRegression() or DecisionTreeClassifier()

---

## 🎯 Goal

> Try to get high test accuracy **without overfitting**

---

## 🔥 Key Idea

> You are balancing:
- Model simplicity  
- Model performance  

---

## 💡 Hint

> Look for a model where:
- Train accuracy ≈ Test accuracy  
- Test accuracy is as high as possible